#!/usr/bin/env python3
"""
Step 3: Train MEPFL models (RandomForest + MLPClassifier).

Reads fault injection pkl files generated by step2, converts raw CSV rows
into Trace/Span objects, trains anomaly detection and service localization models.

Outputs:
    - mepfl_model_gaia/rf_model.pkl   (RandomForest for anomaly classification)
    - mepfl_model_gaia/mlp_model.pkl   (MLP for service-level root cause localization)

Usage:
    python scripts/step3_train_mepfl.py
    python scripts/step3_train_mepfl.py --train-days 5 --max-faults 2429
"""

import argparse
import os
import pickle
import sys
from datetime import datetime
from collections import defaultdict

import numpy as np
from loguru import logger
from tqdm import tqdm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from data.data_models import Span, Trace

# Same service list as in mepfl.py
TOTAL_SERVICE_LIST = [
    'webservice1', 'webservice2', 'redisservice2', 'redisservice1',
    'mobservice1', 'logservice1', 'mobservice2', 'logservice2',
    'dbservice2', 'dbservice1'
]

SERVICE_INDEX_DICT = {
    service: index
    for index, service in enumerate(TOTAL_SERVICE_LIST)
}


def build_traces_from_rows(rows):
    """Convert raw CSV row dicts into Trace/Span object trees.

    Groups rows by trace_id, builds Span objects with parent-child relationships,
    then assembles Trace objects with root_span pointers.

    Args:
        rows: List of dicts with GAIA trace CSV columns

    Returns:
        list of Trace objects
    """
    # Group by trace_id
    trace_id_spans = defaultdict(list)
    for row in rows:
        trace_id = row.get('trace_id', '')
        if not trace_id:
            continue
        trace_id_spans[trace_id].append(row)

    trace_list = []
    for trace_id, span_rows in trace_id_spans.items():
        # Build Span objects
        span_dict = {}  # span_id -> Span
        for row in span_rows:
            span_id = row.get('span_id', '')
            parent_id = row.get('parent_id', '')

            # Parse start/end times
            try:
                start_time_str = row.get('start_time', '')
                if '.' in start_time_str:
                    start_time = datetime.strptime(start_time_str, '%Y-%m-%d %H:%M:%S.%f')
                else:
                    start_time = datetime.strptime(start_time_str, '%Y-%m-%d %H:%M:%S')
            except (ValueError, TypeError):
                continue

            try:
                end_time_str = row.get('end_time', '')
                if '.' in end_time_str:
                    end_time = datetime.strptime(end_time_str, '%Y-%m-%d %H:%M:%S.%f')
                else:
                    end_time = datetime.strptime(end_time_str, '%Y-%m-%d %H:%M:%S')
            except (ValueError, TypeError):
                continue

            duration = (end_time - start_time).total_seconds() * 1000  # milliseconds

            span = Span(
                trace_id=trace_id,
                span_id=span_id,
                parent_span_id=parent_id if parent_id and parent_id != '0' else None,
                children_span_list=[],
                start_time=start_time,
                duration=duration,
                service_name=row.get('service_name', ''),
                status_code=row.get('status_code', '200'),
            )
            span_dict[span_id] = span

        if not span_dict:
            continue

        # Build parent-child relationships
        root_span = None
        for span in span_dict.values():
            if span.parent_span_id is None or span.parent_span_id == '':
                root_span = span
            elif span.parent_span_id in span_dict:
                span_dict[span.parent_span_id].children_span_list.append(span)

        if root_span is None:
            # If no root found, use the first span as root
            root_span = next(iter(span_dict.values()))

        trace = Trace(
            trace_id=trace_id,
            root_span=root_span,
            span_count=len(span_dict),
        )
        trace_list.append(trace)

    return trace_list


def get_trace_service_list(trace):
    """Extract set of service names from a Trace via BFS traversal."""
    service_name_set = set()
    queue = [trace.root_span]
    while queue:
        span = queue.pop(0)
        queue.extend(span.children_span_list)
        service_name_set.add(span.service_name)
    return service_name_set


def get_trace_list_vector(trace_list):
    """Compute feature vectors for a list of Traces.

    Each trace gets a vector of dimension 2 + len(TOTAL_SERVICE_LIST) * 3 = 32.
    Features: [total_services, num_services_in_trace, (duration, status, process_time) per service]

    This replicates the logic from mepfl.py:get_trace_list_vector().
    """
    for trace in trace_list:
        trace.vector = np.zeros((2 + len(TOTAL_SERVICE_LIST) * 3))
        trace.vector[0] = len(TOTAL_SERVICE_LIST)
        trace.vector[1] = len(get_trace_service_list(trace))

        queue = [trace.root_span]
        while queue:
            span = queue.pop(0)
            temp_list = sorted(span.children_span_list, key=lambda x: x.start_time, reverse=False)
            queue.extend(temp_list)

            duration = span.duration
            # Convert status code
            if span.status_code in ('Ok', 'OK', '200'):
                status = 0
            else:
                try:
                    status = int(span.status_code)
                except (ValueError, TypeError):
                    status = 0
            process_time = span.duration - max(
                [child.duration for child in span.children_span_list], default=0.0
            )

            idx = SERVICE_INDEX_DICT.get(span.service_name)
            if idx is not None:
                trace.vector[-1 + (idx + 1) * 3] = duration
                trace.vector[0 + (idx + 1) * 3] = status
                trace.vector[1 + (idx + 1) * 3] = process_time


def build_training_set(file_list, datasets_root, max_faults):
    """Build training data from fault injection pkl files.

    Args:
        file_list: List of pkl filenames to use for training
        datasets_root: Path to Datasets/GAIA
        max_faults: Maximum number of fault injections to use for training

    Returns:
        (classification_traces, localization_traces, test_fault_injections)
    """
    classification_traces = []
    localization_traces = []
    test_fault_injections = []
    valid_fault_count = 0

    for filename in file_list:
        pkl_path = os.path.join(datasets_root, 'fault_injection_tracerank', filename)
        if not os.path.exists(pkl_path):
            logger.warning(f"File not found: {pkl_path}")
            continue

        fault_injection_list = pickle.load(open(pkl_path, 'rb'))
        logger.info(f"Loaded {filename}, {len(fault_injection_list)} fault injections")

        for fault_injection in fault_injection_list:
            if valid_fault_count >= max_faults:
                test_fault_injections.append(fault_injection)
                continue

            rows = fault_injection['trace_list']
            trace_list = build_traces_from_rows(rows)

            if len(trace_list) <= 10:
                continue

            valid_fault_count += 1
            fault_service = fault_injection['service']
            fault_time = fault_injection['time']

            for trace in trace_list:
                time_diff = (trace.root_span.start_time - fault_time).total_seconds()
                if time_diff <= 60 and fault_service in get_trace_service_list(trace):
                    # Anomaly trace: within 60s and contains fault service
                    trace.anomaly_type = 1
                    trace.fault_service_index = SERVICE_INDEX_DICT[fault_service]
                    classification_traces.append(trace)
                    localization_traces.append(trace)
                else:
                    # Normal trace
                    trace.anomaly_type = 0
                    classification_traces.append(trace)

    logger.info(f"Training set: {len(classification_traces)} classification, "
                f"{len(localization_traces)} localization, "
                f"{len(test_fault_injections)} test faults")
    return classification_traces, localization_traces, test_fault_injections


def parse_args():
    parser = argparse.ArgumentParser(
        description='Step 3: Train MEPFL models (RandomForest + MLPClassifier)'
    )
    parser.add_argument(
        '--datasets-root', type=str, default='./Datasets/GAIA',
        help='Path to Datasets/GAIA'
    )
    parser.add_argument(
        '--output-dir', type=str, default='./mepfl_model_gaia',
        help='Output directory for trained models'
    )
    parser.add_argument(
        '--train-days', type=int, default=5,
        help='Number of pkl files to use for training (rest for testing)'
    )
    parser.add_argument(
        '--max-faults', type=int, default=2429,
        help='Maximum number of fault injections for training'
    )
    return parser.parse_args()


def main():
    args = parse_args()

    # List available pkl files
    pkl_dir = os.path.join(args.datasets_root, 'fault_injection_tracerank')
    if not os.path.isdir(pkl_dir):
        logger.error(f"Directory not found: {pkl_dir}. Run step2 first.")
        sys.exit(1)

    file_list = sorted([f for f in os.listdir(pkl_dir) if f.endswith('.pkl')])
    if not file_list:
        logger.error(f"No pkl files found in {pkl_dir}. Run step2 first.")
        sys.exit(1)

    logger.info(f"Found {len(file_list)} pkl files, using first {args.train_days} for training")

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)

    # Build training set
    train_files = file_list[:args.train_days]
    cls_traces, loc_traces, test_faults = build_training_set(
        train_files, args.datasets_root, args.max_faults
    )

    if not cls_traces:
        logger.error("No training data generated. Check pkl files.")
        sys.exit(1)

    # Compute feature vectors
    logger.info("Computing feature vectors for classification traces...")
    get_trace_list_vector(cls_traces)
    get_trace_list_vector(loc_traces)

    # Train RandomForest for anomaly classification
    logger.info("Training RandomForest for anomaly classification...")
    cls_x = np.array([t.vector for t in cls_traces])
    cls_y = np.array([t.anomaly_type for t in cls_traces])

    rf_model = RandomForestClassifier(random_state=0)
    rf_model.fit(cls_x, cls_y)

    # Quick evaluation
    sample_size = min(10000, len(cls_y))
    pred = rf_model.predict(cls_x[:sample_size])
    acc = accuracy_score(cls_y[:sample_size], pred)
    logger.info(f"RF training accuracy (sample): {acc:.4f}")

    # Train MLP for service localization
    logger.info("Training MLP for service localization...")
    loc_x = np.array([t.vector for t in loc_traces])
    loc_y = np.array([t.fault_service_index for t in loc_traces])

    mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
    mlp_model.fit(loc_x, loc_y)

    sample_size = min(10000, len(loc_y))
    pred = mlp_model.predict(loc_x[:sample_size])
    acc = accuracy_score(loc_y[:sample_size], pred)
    logger.info(f"MLP training accuracy (sample): {acc:.4f}")

    # Save models
    rf_path = os.path.join(args.output_dir, 'rf_model.pkl')
    mlp_path = os.path.join(args.output_dir, 'mlp_model.pkl')
    test_path = os.path.join(args.output_dir, 'temp_fault_injection.pkl')

    pickle.dump(rf_model, open(rf_path, 'wb'))
    pickle.dump(mlp_model, open(mlp_path, 'wb'))
    pickle.dump(test_faults, open(test_path, 'wb'))

    logger.info(f"Saved RF model: {rf_path}")
    logger.info(f"Saved MLP model: {mlp_path}")
    logger.info("Step 3 complete.")


if __name__ == '__main__':
    main()
